### ISSUE TITLE
Seg Fault

### ISSUE THREAD

**Issue by m516** [ellensp/rrd-glcd-tester#1]
I copied and pasted the code from this repository directly into the Arduino IDE and got the following message:

```
Path\To\Libraries\U8glib\src\clib\u8g_rect.c: In function 'u8g_draw_hline.constprop':

Path\To\Libraries\U8glib\src\clib\u8g_rect.c:57:1: internal compiler error: Segmentation fault

 }

 ^

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.19.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/program files/windowsapps/arduinollc.arduinoide_1.8.19.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
```

This was after I U8glib from the package manager built into the Windows 10 Arduino IDE. After poking around for a bit, I found out that the rectangle function in U8glib will crash if you try to draw out of the screen's boundaries. I changed line 131 from 
`u8g.drawBox(0,0,128,64);`
to 
`u8g.drawBox(0,0,127,63);`
And then it complied. Thank you for the code!

**Comment by ellensp** [comment]
from https://github.com/olikraus/u8glib/wiki/userreference#drawbox
"Description: Draw a box (filled frame), starting at x/y position (upper left edge). The box has width w and height h. Parts of the box can be outside of the display boundaries." 

It still compiles fine on latest Arduino IDE and libraries on Linux

This looks to be a bug in the windows app version of the Arduino IDE.

**Comment by m516** [comment]
All right, so the problem isn't in this repository. Thanks for the input!
