### ISSUE TITLE
Screen shows all pixels filled (wrong controller used)

### ISSUE THREAD

**Issue by rocketkittens** [ellensp/rrd-glcd-tester#2]
I expected some text to show when i load the program, but i get a full screen of pixels.
Marlin works on my LCD when i load it.

**Comment by ellensp** [comment]
Tester is for REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER not REPRAP_DISCOUNT_SMART_CONTROLLER

**Comment by rocketkittens** [comment]
Thanks for pointing that out @ellensp, i was directed here by mistake and i resolved my original issue a minute ago.
https://github.com/MarlinFirmware/Marlin/issues/15896

I have a Full Graphic Smart Controller so i will save this program for later when i can try it for real. Thanks for your work!
