### ISSUE TITLE
Other MEGA/RAMPS 1.4 sketches

### ISSUE THREAD

**Issue by DQUEROL** [ellensp/rrd-glcd-tester#3]
I am not certain if this is the way to contact you, but I found no other way.
Three questions:
1. Have you developed or seen a similar testing firmware for the old RepRap2004LCD? 
2. Have you seen examples of its use (with Encoder, SD) without marlin or its equivalents?
3. Where could I get sketches of the use of the RAMPS1.4 outside 3dprinting?
Thank you for your help.
Best regards
Daniel Querol

**Comment by ellensp** [comment]
that would be in my other repository  https://github.com/ellensp/rrd-lcd-tester 
RepRap2004LCD looks to be a clone of the reprap discount 20x4 LCD
