### ISSUE TITLE
Rotary Encoder only incrementing value not decrementing 

### ISSUE THREAD

**Issue by bhushan0000** [ellensp/rrd-glcd-tester#4]
hello guys i am using marlin 1.1 with ramps 1.4 i am unable to get encoder working when i press it i goes to menu but thats it its not scrolling through menu 
so i searched on get and found this glcd tester ...
i also tried replacing the encoder  also encoder shows short between ground and pin b

**Comment by ellensp** [comment]
Clearly a hardware issue. What on earth do you think I can do about your hardware issue?

**Comment by bhushan0000** [comment]
Sir its not hardware issue i clearly stated that i replaced it with new
encoder which i checked before soldering

**Comment by ellensp** [comment]
Is still a fault, probably a dead, dying  IO pin on mega.
Use https://www.arduino.cc/en/Tutorial/BuiltInExamples/Button and test out the input to both pins
BTN_EN1         31
BTN_EN2         33
